/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author JohnReedLOL
 */
public class JFrame_GUI extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_GUI
     */
    public JFrame_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        outgoingChatjTextField_ = new javax.swing.JTextField();
        incomingChatjScrollPane_ = new javax.swing.JScrollPane();
        incomingChatjTextArea_ = new javax.swing.JTextArea();
        inventoryStatsEquipmentjTabbedPane_ = new javax.swing.JTabbedPane();
        playerStatsjScrollPane_ = new javax.swing.JScrollPane();
        playerStatsjTextArea_ = new javax.swing.JTextArea();
        playerInventoryjPanel = new javax.swing.JPanel();
        item2jLabel_ = new javax.swing.JLabel();
        item4jLabel_ = new javax.swing.JLabel();
        item1jLabel_ = new javax.swing.JLabel();
        item3jLabel_ = new javax.swing.JLabel();
        playerEquipmentjPanel_ = new javax.swing.JPanel();
        weaponSlotjLabel_ = new javax.swing.JLabel();
        helmetjLabel_1 = new javax.swing.JLabel();
        sheildSlotjLabel_ = new javax.swing.JLabel();
        playerSpecialjPanel_ = new javax.swing.JPanel();
        specialjButton1_ = new javax.swing.JButton();
        specialjButton2_ = new javax.swing.JButton();
        specialjButton3_ = new javax.swing.JButton();
        specialjButton4_ = new javax.swing.JButton();
        optionsjPanel_ = new javax.swing.JPanel();
        musicOptionjRadioButton_ = new javax.swing.JRadioButton();
        soundOptionjRadioButton_ = new javax.swing.JRadioButton();
        playerControlsjScrollPane_ = new javax.swing.JScrollPane();
        playerControlsjTextArea_ = new javax.swing.JTextArea();
        game_Screen_JPanel1 = new View.Game_Screen_JPanel();
        minimap_JTextPanel1 = new View.Minimap_JTextPanel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome to RunarScape");
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        outgoingChatjTextField_.setText("outgoingChatjTextField_");
        outgoingChatjTextField_.setFocusable(false);

        incomingChatjTextArea_.setColumns(20);
        incomingChatjTextArea_.setRows(5);
        incomingChatjTextArea_.setText("incomingChatjTextArea_");
        incomingChatjScrollPane_.setViewportView(incomingChatjTextArea_);

        playerStatsjTextArea_.setColumns(20);
        playerStatsjTextArea_.setRows(5);
        playerStatsjTextArea_.setText("playerStatsjTextArea_");
        playerStatsjTextArea_.setFocusable(false);
        playerStatsjScrollPane_.setViewportView(playerStatsjTextArea_);

        inventoryStatsEquipmentjTabbedPane_.addTab("Stats", playerStatsjScrollPane_);

        item2jLabel_.setText("item2jLabel_");
        item2jLabel_.setPreferredSize(new java.awt.Dimension(80, 80));

        item4jLabel_.setText("item4jLabel_");
        item4jLabel_.setPreferredSize(new java.awt.Dimension(80, 80));

        item1jLabel_.setText("item1jLabel_");
        item1jLabel_.setPreferredSize(new java.awt.Dimension(80, 80));

        item3jLabel_.setText("item3jLabel_");
        item3jLabel_.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout playerInventoryjPanelLayout = new javax.swing.GroupLayout(playerInventoryjPanel);
        playerInventoryjPanel.setLayout(playerInventoryjPanelLayout);
        playerInventoryjPanelLayout.setHorizontalGroup(
            playerInventoryjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerInventoryjPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(playerInventoryjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(playerInventoryjPanelLayout.createSequentialGroup()
                        .addComponent(item1jLabel_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(item2jLabel_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playerInventoryjPanelLayout.createSequentialGroup()
                        .addComponent(item3jLabel_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(item4jLabel_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        playerInventoryjPanelLayout.setVerticalGroup(
            playerInventoryjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerInventoryjPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(playerInventoryjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item1jLabel_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item2jLabel_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(playerInventoryjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item4jLabel_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item3jLabel_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        inventoryStatsEquipmentjTabbedPane_.addTab("Items", playerInventoryjPanel);

        weaponSlotjLabel_.setText("weaponSlotjLabel_");
        weaponSlotjLabel_.setPreferredSize(new java.awt.Dimension(80, 80));

        helmetjLabel_1.setText("helmetjLabel_");
        helmetjLabel_1.setPreferredSize(new java.awt.Dimension(80, 80));

        sheildSlotjLabel_.setText("sheildSlotjLabel_");
        sheildSlotjLabel_.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout playerEquipmentjPanel_Layout = new javax.swing.GroupLayout(playerEquipmentjPanel_);
        playerEquipmentjPanel_.setLayout(playerEquipmentjPanel_Layout);
        playerEquipmentjPanel_Layout.setHorizontalGroup(
            playerEquipmentjPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playerEquipmentjPanel_Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sheildSlotjLabel_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(weaponSlotjLabel_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playerEquipmentjPanel_Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(helmetjLabel_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        playerEquipmentjPanel_Layout.setVerticalGroup(
            playerEquipmentjPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playerEquipmentjPanel_Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(helmetjLabel_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(playerEquipmentjPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sheildSlotjLabel_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weaponSlotjLabel_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95))
        );

        inventoryStatsEquipmentjTabbedPane_.addTab("Gear", playerEquipmentjPanel_);

        specialjButton1_.setText("specialjButton1_");

        specialjButton2_.setText("specialjButton2_");

        specialjButton3_.setText("specialjButton3_");

        specialjButton4_.setText("specialjButton4_");

        javax.swing.GroupLayout playerSpecialjPanel_Layout = new javax.swing.GroupLayout(playerSpecialjPanel_);
        playerSpecialjPanel_.setLayout(playerSpecialjPanel_Layout);
        playerSpecialjPanel_Layout.setHorizontalGroup(
            playerSpecialjPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerSpecialjPanel_Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(playerSpecialjPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(specialjButton1_, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(specialjButton2_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(specialjButton3_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(specialjButton4_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        playerSpecialjPanel_Layout.setVerticalGroup(
            playerSpecialjPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerSpecialjPanel_Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(specialjButton1_, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(specialjButton2_, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(specialjButton3_, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(specialjButton4_, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        inventoryStatsEquipmentjTabbedPane_.addTab("Special", playerSpecialjPanel_);

        musicOptionjRadioButton_.setText("musicOptionjRadioButton_");
        musicOptionjRadioButton_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicOptionjRadioButton_ActionPerformed(evt);
            }
        });

        soundOptionjRadioButton_.setText("soundOptionjRadioButton_");
        soundOptionjRadioButton_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundOptionjRadioButton_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionsjPanel_Layout = new javax.swing.GroupLayout(optionsjPanel_);
        optionsjPanel_.setLayout(optionsjPanel_Layout);
        optionsjPanel_Layout.setHorizontalGroup(
            optionsjPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsjPanel_Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(optionsjPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(musicOptionjRadioButton_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(soundOptionjRadioButton_, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        optionsjPanel_Layout.setVerticalGroup(
            optionsjPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsjPanel_Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(musicOptionjRadioButton_, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(soundOptionjRadioButton_, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(195, Short.MAX_VALUE))
        );

        inventoryStatsEquipmentjTabbedPane_.addTab("Options", optionsjPanel_);

        playerControlsjTextArea_.setColumns(20);
        playerControlsjTextArea_.setRows(5);
        playerControlsjTextArea_.setText("playerControlsjTextArea_");
        playerControlsjTextArea_.setFocusable(false);
        playerControlsjScrollPane_.setViewportView(playerControlsjTextArea_);

        inventoryStatsEquipmentjTabbedPane_.addTab("Controls", playerControlsjScrollPane_);

        javax.swing.GroupLayout game_Screen_JPanel1Layout = new javax.swing.GroupLayout(game_Screen_JPanel1);
        game_Screen_JPanel1.setLayout(game_Screen_JPanel1Layout);
        game_Screen_JPanel1Layout.setHorizontalGroup(
            game_Screen_JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        game_Screen_JPanel1Layout.setVerticalGroup(
            game_Screen_JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        minimap_JTextPanel1.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout minimap_JTextPanel1Layout = new javax.swing.GroupLayout(minimap_JTextPanel1);
        minimap_JTextPanel1.setLayout(minimap_JTextPanel1Layout);
        minimap_JTextPanel1Layout.setHorizontalGroup(
            minimap_JTextPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        minimap_JTextPanel1Layout.setVerticalGroup(
            minimap_JTextPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(outgoingChatjTextField_)
                    .addComponent(incomingChatjScrollPane_, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                    .addComponent(game_Screen_JPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(minimap_JTextPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inventoryStatsEquipmentjTabbedPane_, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(minimap_JTextPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventoryStatsEquipmentjTabbedPane_, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(game_Screen_JPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(incomingChatjScrollPane_, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(outgoingChatjTextField_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyTyped

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formMousePressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowLostFocus

    private void soundOptionjRadioButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundOptionjRadioButton_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soundOptionjRadioButton_ActionPerformed

    private void musicOptionjRadioButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicOptionjRadioButton_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_musicOptionjRadioButton_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private View.Game_Screen_JPanel game_Screen_JPanel1;
    private javax.swing.JLabel helmetjLabel_1;
    private javax.swing.JScrollPane incomingChatjScrollPane_;
    private javax.swing.JTextArea incomingChatjTextArea_;
    private javax.swing.JTabbedPane inventoryStatsEquipmentjTabbedPane_;
    private javax.swing.JLabel item1jLabel_;
    private javax.swing.JLabel item2jLabel_;
    private javax.swing.JLabel item3jLabel_;
    private javax.swing.JLabel item4jLabel_;
    private javax.swing.JMenuItem jMenuItem1;
    private View.Minimap_JTextPanel minimap_JTextPanel1;
    private javax.swing.JRadioButton musicOptionjRadioButton_;
    private javax.swing.JPanel optionsjPanel_;
    private javax.swing.JTextField outgoingChatjTextField_;
    private javax.swing.JScrollPane playerControlsjScrollPane_;
    private javax.swing.JTextArea playerControlsjTextArea_;
    private javax.swing.JPanel playerEquipmentjPanel_;
    private javax.swing.JPanel playerInventoryjPanel;
    private javax.swing.JPanel playerSpecialjPanel_;
    private javax.swing.JScrollPane playerStatsjScrollPane_;
    private javax.swing.JTextArea playerStatsjTextArea_;
    private javax.swing.JLabel sheildSlotjLabel_;
    private javax.swing.JRadioButton soundOptionjRadioButton_;
    private javax.swing.JButton specialjButton1_;
    private javax.swing.JButton specialjButton2_;
    private javax.swing.JButton specialjButton3_;
    private javax.swing.JButton specialjButton4_;
    private javax.swing.JLabel weaponSlotjLabel_;
    // End of variables declaration//GEN-END:variables
}
