/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.viewport;

import java.util.ArrayList;
import model.ModelViewBundle;
import mvc_bridgeway.control_map.ControlMap;

/**
 *
 * @author JohnReedLOL
 */
public class GameControlsViewport extends Viewport {

    /**
     * Creates new form GameControlsViewport
     */
    public GameControlsViewport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        controlsSplitPane_ = new javax.swing.JSplitPane();
        keysScrollPane_left_ = new javax.swing.JScrollPane();
        keysjTextArea_left_ = new javax.swing.JTextArea();
        gameControlsScrollPane_right_ = new javax.swing.JScrollPane();
        controlsjTextArea_right_ = new javax.swing.JTextArea();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        controlsSplitPane_.setDividerLocation(150);

        keysjTextArea_left_.setColumns(20);
        keysjTextArea_left_.setRows(5);
        keysjTextArea_left_.setText("Keys:\n");
        keysScrollPane_left_.setViewportView(keysjTextArea_left_);

        controlsSplitPane_.setLeftComponent(keysScrollPane_left_);

        controlsjTextArea_right_.setColumns(20);
        controlsjTextArea_right_.setRows(5);
        controlsjTextArea_right_.setText("Actions:\n");
        gameControlsScrollPane_right_.setViewportView(controlsjTextArea_right_);

        controlsSplitPane_.setRightComponent(gameControlsScrollPane_right_);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(controlsSplitPane_, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(controlsSplitPane_, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane controlsSplitPane_;
    private javax.swing.JTextArea controlsjTextArea_right_;
    private javax.swing.JScrollPane gameControlsScrollPane_right_;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JScrollPane keysScrollPane_left_;
    private javax.swing.JTextArea keysjTextArea_left_;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(ModelViewBundle mvb) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public ArrayList<ControlMap> getControlMaps() {
        ArrayList<ControlMap> controlMaps = new ArrayList<ControlMap>();
        // TODOD
        return controlMaps;
    }

    @Override
    protected void generateView() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
