/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.viewport;

import application.Application;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

import model.ModelViewBundle;
import model.armory.Armory;
import model.entity.Entity;
import model.entity.avatar.Avatar;
import model.entity.stats.SmasherStats;
import model.entity.stats.SmasherStatsVisitor;
import model.entity.stats.SneakStats;
import model.entity.stats.SneakStatsOwnership;
import model.entity.stats.SneakStatsVisitor;
import model.entity.stats.Stats;
import model.entity.stats.StatsOwnership;
import model.entity.stats.StatsVisitor;
import model.entity.stats.SummonerStats;
import model.entity.stats.SummonerStatsVisitor;
import model.inventory.Sack;
import mvc_bridgeway.command.model_command.ExitCommand;
import mvc_bridgeway.control.virtual_control.swing_control.SwingControl;
import mvc_bridgeway.control_map.ControlMap;

public class StatsViewport extends Viewport {


    public StatsViewport() {
        initComponents();
        generateView();
    }

    @Override
    public void update(ModelViewBundle mvb) {
        StatsOwnership stats = mvb.getAvatar().getStatsOwnership();
        displayStats(stats);
    }

    @Override
    public ArrayList<ControlMap> getControlMaps() {
        ArrayList<ControlMap> controlMaps = new ArrayList<ControlMap>();
        //TODOD
        return controlMaps;
    }

    @Override
    protected void generateView() {
        //
    }
    
    private void displayStats(StatsOwnership stats) {
        //
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stats_jScrollPane_ = new javax.swing.JScrollPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stats_jScrollPane_, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stats_jScrollPane_, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane stats_jScrollPane_;
    // End of variables declaration//GEN-END:variables

}
